# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1539934c8f208e56daaec81e3734021f1685310f843196123bad4d82e79a70a95bebf951b1b4adc7cd127d7e443a39668f9c206d80652786ad307f12ab8348b4

test:
  secret_key_base: 33bfd9bc7ee9ddfee2a219f2b0ae456fcd50858f8bab14cb28a140618c7af85ae2d478b109628ef16aadd2a5ac33dcef753d363f2d9d3bfab973e09bbb51cd5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
